name: multi line commands demo
on:
  workflow_dispatch:
jobs:
  multi-line:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v6
      - name: Execute multiple commands in single step 
        run: |
          uptime 
          ls -ltrh 
          ls -la 
          pwd 
          uname -a 
          id -u 
          cat devops .txt