name: Testing Workflow
on: 
  push:
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Display 
        run: echo "Hello Kiyansh"
      - name: Display The Date
        run: date